feat: first update into inditexTech to aling and save code
InditexTech/argo-workflows pull request #1
Opened 2024-03-21 10:01 UTC by jonathanCaamano

Fixes #TODO

### Motivation

### Modifications

### Verification

2024-03-22 13:22 UTC, DanielDorado requested changes

2024-03-22 13:22 UTC, DanielDorado commented on server/auth/sso/sso.go
> +	configOauth := &oauth2.Config{
We have to do that this variable name was not changed from config because it affects a lot of lines that should not see as changed.

Maybe doing that  in the line before to this one is enough:

``` go
SSOExtendedLabel := config.SSOExtendedLabel
``` 

Then, thought the config var is overwritten we can use their type with this new name.

2024-03-22 13:22 UTC, DanielDorado commented on server/auth/types/claims.go
> +	TeamClaimsFilter        TeamClaimsFilter       `json:"TeamClaimsFilter,omitempty"`
The name *TeamClaimsFilter* is incorrect because it is not a Filter. "TeamFlilterClaims" is better if you can have the

2024-03-22 13:22 UTC, DanielDorado commented on server/auth/sso/sso.go
> +		TeamClaimsFilter: types.TeamClaimsFilter{
With these values, how do you know if we can skip the filter?

What is the difference between a user without any values and an admin that does not have values?

2024-03-22 13:22 UTC, DanielDorado commented on server/auth/sso/sso.go
> +			Filter: c.TeamClaimsFilter.Filter,
Change the name to something a little more understandable: FilterExpression.

2024-03-22 13:59 UTC, jonathanCaamano commented on config/sso_extended.go
> +	AdminGroup  string `json:"adminGroup,omitempty"`
Done

2024-03-22 14:00 UTC, jonathanCaamano commented on config/sso_extended.go
> +	return true
Done

2024-03-22 14:10 UTC, jonathanCaamano commented on config/sso_extended.go
> +func RbacDelegateToLabel(ctx context.Context, name string, apiUrl, apiPassword, label string) (string, []string, string, error) {
Done

2024-03-22 14:23 UTC, jonathanCaamano commented on config/sso_extended.go
> +	roles, err := devhub.GetDevhubRoles(devhubClient, apiUrl, apiPassword, name)
Done

2024-03-22 14:23 UTC, jonathanCaamano commented on server/auth/devhub/aplication.go
> +
Done

2024-03-22 14:25 UTC, jonathanCaamano commented on server/auth/sso/null_sso.go
> +func (n nullService) OpenAmConfig() *config.SSOExtendedLabel {
Done

2024-03-22 14:27 UTC, jonathanCaamano commented on server/auth/sso/sso.go
> +	configOauth := &oauth2.Config{
Done

2024-03-22 14:27 UTC, jonathanCaamano commented on server/auth/types/claims.go
> +	TeamClaimsFilter        TeamClaimsFilter       `json:"TeamClaimsFilter,omitempty"`
Done

2024-03-22 14:27 UTC, jonathanCaamano commented on server/auth/sso/sso.go
> +		TeamClaimsFilter: types.TeamClaimsFilter{
Done

2024-04-10 06:57 UTC, DanielDorado approved these changes

2024-04-10 06:57 UTC, DanielDorado commented on config/sso_extended.go
> +	resourcesToFilterPopulated.Group = getUserGroup(servicesAndRoles.Roles)
The plugin (module devhub for now) should return the group.

2024-04-10 06:57 UTC, DanielDorado commented on server/auth/devhub/client.go
> +	resp, err := c.HTTPClient.Do(req)
Add Retries with a Backoff Strategy. This should be in all production programs.

Use the library used by argoworkflows to retries.

2024-04-10 06:57 UTC, DanielDorado commented on server/auth/sso/sso.go
> +	ssoExtendedConfigurate.AdminGroup = c.SSOExtendedLabel.AdminGroup
```suggestion
	ssoExtendedConfigurate = c.SSOExtendedLabel
```

2024-07-05 07:51 UTC, merged