feat: support contributors
InditexTech/argo-workflows pull request #7
Opened 2024-10-30 16:16 UTC by jonathanCaamano

Closes https://github.com/inditex/iac-sentijobs/issues/142

2024-11-14 11:04 UTC, Dav1dPF requested changes

2024-11-14 11:04 UTC, Dav1dPF commented on workflow/filter/filter.go
>  			}
```suggestion
	for key, relationship := range ctx.Value(auth.ClaimsKey).(*argoTypes.Claims).TeamFilterClaims.Values {
		if key != labels[ctx.Value(auth.ClaimsKey).(*argoTypes.Claims).TeamFilterClaims.Label] {
		      continue
		}
                if ctx.Value(auth.ClaimsKey).(*argoTypes.Claims).TeamFilterClaims.EnvToFilter != "pro" || ( relationship == "Owner" && ctx.Value(auth.ClaimsKey).(*argoTypes.Claims).TeamFilterClaims.Group == "writer"){
                return true
                }
```

2024-11-14 13:00 UTC, jonathanCaamano commented on server/auth/devhub/aplication.go
>  			}
Done

2024-11-14 13:00 UTC, jonathanCaamano commented on server/cronworkflow/cron_workflow_server.go
> +	var hasPermission bool
Done

2024-11-14 13:00 UTC, jonathanCaamano commented on server/cronworkflow/cron_workflow_server.go
> +	}
Done

2024-11-14 13:00 UTC, jonathanCaamano commented on server/workflow/workflow_server.go
> +	var hasPermission bool
Done

2024-11-14 13:01 UTC, jonathanCaamano commented on workflow/filter/filter.go
>  			}
done

2024-11-15 09:02 UTC, DanielDorado requested changes

2024-11-15 09:02 UTC, DanielDorado commented on workflow/filter/filter.go
> +		if ctx.Value(auth.ClaimsKey).(*argoTypes.Claims).TeamFilterClaims.EnvToFilter != "pro" || (relationship == "Owner" && ctx.Value(auth.ClaimsKey).(*argoTypes.Claims).TeamFilterClaims.Group == "writer
Here, we do not want to know what environment we are in. Only if for a service it is a "writer" or a "reader".

This should be done with the SSO configuration.

- What Roles (and Relationship: Owner or Contributor) have what Group.

This way, we do not pollute Argo workflows with this logic.

2024-11-15 12:38 UTC, jonathanCaamano commented on server/auth/devhub/aplication.go
> +	Services map[string]string
Done

2024-11-15 12:38 UTC, jonathanCaamano commented on config/sso_extended.go
>  	}
Done

2024-11-15 12:38 UTC, jonathanCaamano commented on workflow/filter/filter.go
> +		if ctx.Value(auth.ClaimsKey).(*argoTypes.Claims).TeamFilterClaims.EnvToFilter != "pro" || (relationship == "Owner" && ctx.Value(auth.ClaimsKey).(*argoTypes.Claims).TeamFilterClaims.Group == "writer
Done

2024-11-15 12:57 UTC, DanielDorado approved these changes

2024-11-15 13:05 UTC, merged